# Generated by Django 4.1.3 on 2023-10-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('Educationlevel', models.CharField(max_length=256)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSKRU.category')),
            ],
        ),
    ]
